apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: web-app-stage
  labels:
    app: goapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: web
        image: ksxack/lesson1:v0.2 ## Используйте свой Образ
        ports:
        - containerPort: 8080