apiVersion: v1
kind: Pod
metadata:
  name: simple-web
  namespace: web-app-dev
spec:
  containers:
    - name: web
      image: docker.io/developer/py_app:v0.1
      imagePullPolicy: Never  # Важно! Не пытаться загружать из реестра
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP